[tool.poetry]
name = "scfiles"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lz4 = {extras = ["block"], version = "^4.3.2"}

[tool.poetry.dev-dependencies]
rich = "^13.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
