[tool.poetry]
name = "sc-file"
version = "3.0.0-dev.6"
description = "Library & Utility for converting stalcraft files"
authors = ["onejeuu <bloodtrail@beber1k.ru>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "scfile" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
lz4 = "^4.3.2"
click = "^8.1.7"
quicktex = "^0.2.0"
numpy = "^1.26.3"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.0.0"
rich = "^13.0.0"

[tool.poetry.scripts]
build = "build:build"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
