[tool.poetry]
name = "scfiles"
version = "1.3.0"
description = ""
authors = ["onejeuu <bloodtrail@beber1k.ru>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scfile"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
lz4 = {extras = ["block"], version = "^4.3.2"}

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.1.0"
rich = "^13.5.3"

[tool.poetry.scripts]
build = "build:build"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["E501"]
