name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Binary
        run: python scripts/build.py

      - name: Prepare Windows Artifact
        shell: bash
        run: |
          mv dist/scfile.exe scfile_windows_x64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: scfile_windows_x64.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Binary
        run: python scripts/build.py

      - name: Prepare Linux Artifact
        run: |
          mv dist/scfile scfile_linux_x64
          chmod +x scfile_linux_x64

      - uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: scfile_linux_x64

  create-release:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]

    steps:
      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: artifacts

      - name: Download Linux Binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: artifacts

      - name: Get Current date
        id: date
        run: echo "date=$(date +'%B %d, %Y')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🏷 **Version:** `${{ github.ref_name }}`
            📅 **Date:** `${{ steps.date.outputs.date }}`

            **Linux** (x86_64): `scfile_linux_x64`
            **Windows** (x64): `scfile_windows_x64.exe`
          files: |
            artifacts/scfile_windows_x64.exe
            artifacts/scfile_linux_x64
