name: Tests

on:
  push:
    paths:
      - "scfile/**"
      - "tests/**"
  pull_request:
    paths:
      - "scfile/**"
      - "tests/**"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install UV
        run: pip install uv

      - name: Install Dependencies
        run: uv sync

      - name: Run Tests
        run: uv run pytest
